# Site settings
title: My Space (To be Scrapped off)
description: "Atri Ghosh personal website."
url: https://atrighosh.github.io
#baseurl: "/about"
repository: "atrighosh/atrighosh.github.io"
author:
  name: Atri Ghosh
  email: 1atrighosh@gmail.com

# Build settings
remote_theme: pages-themes/jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
- jekyll-sitemap

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/atrighosh" }
    - { platform: twitter, user_url: "https://twitter.com/1atrizx" }
  
header_pages:
  - about.md
  - portfolio.md
