# Site settings
title: My Space (To be Scrapped off)
author:
  name: Atri Ghosh
  email: 1atrighosh@gmail.com
description: &description "Atri Ghosh personal website."

locale                   : "en-US"
#title_separator          : "-"
name                     : &name "Atri Ghosh"
url                      : https://atrighosh.github.io
baseurl                  : "/about" # the subpath of your site, e.g. "/blog"
repository               : "atrighosh/atrighosh.github.io"
# Build settings
remote_theme: pages-themes/jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/atrighosh" }
    - { platform: twitter, user_url: "https://twitter.com/1atrizx" }
  
header_pages:
  - about.md
  - portfolio.md
